[service_account]
type = "service_account"
project_id = "gads-mersalg"
private_key_id = "4ee9fc8ca8f4bca2d3c3dc294fe6cc6b229e32ef"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCwvRuGXet4CFWM
7u2uWZGoSFgGl4Y47OYBGqdqUoKhUs0vZa6Vsh78kB/7oEQb9HIVU/AjWJIKXumf
6lqd3WT1NPjzWNrO7c5MCd8FUMZieBoPRDrVsdARTwjmRTNl0VUQh2IuGKXFuqTP
u39WOzOeVc7aUDZrXxr4KcoqqJlOR20NGaU1rX5Y/GtQramgt21l5tXcXEvDu+5C
7oJG/P6LFIbswtL4fWVzM7Muz55EB1r2VWGMk6QGRvrwYUX4sdM8sM88LGMOkyDu
8BCiInneqS5IluK8BVTk4fme+yOLuxnVh4sMlP2lOlNbdUpGrvmR/opGUXZ2YL8j
1q/4UCzZAgMBAAECggEAEcabX5rPpY11CU04o5oHn9zS2argyZXuFjtXjkaJM++P
io5YDl9RZYabaOP4JbWiyclc9Dkiyx87sSVRguIzFsSCq3sK2tgpMRWnFDJJGbtJ
p7JtlnOhYTRJSVu5bSquOxDay5cYCTiZ/fi2OHaQ3QJ1YRjDOG5i2IXfewXlEW3L
lTYSDtvoFXydNMGgeQ9Fof/opemho3EXWEps1dek6Y1Zkik1bzf52PIToBzg8MMg
EHU2+LTl+CfIwiZk3S2lv2cPDygMm0Na6WngCUmKTCgs8gr8YlOpkYTmcQCTU81M
YiSEFo4C5VcY1+uriH2QUm3b7qokCihpzZP3gK5E+QKBgQDuePsKjAEnLNeQIxmQ
norCzelBWNRYLups1/J8bgSnAS3g4eyiKi4j8SsFHeiF78YT4h47yf4SLdJBo87e
KO5u29ey7o9J61WSbmsxIfe5OukFxin2xtcgjVGW0UrlWZN0k5lTK9aV9gLeeXQ0
nY8HnJh7nL68IdLPvdw9CRJ71QKBgQC9upAn3FavjV3wvPSA/V5VI8kzlNKOno7K
Ujv27GPL6Ke+799QWFfMM3y5jf/aJOi27cs9OKMZDr3R8b5ZnQ9XrScUQWAhxFdv
cNE/7ciz85BEYvgthfxcLsQZovxLTve7VtRI9r3YAmhdoz3eIrj0Tv2bro+c5iPe
0J3gLggC9QKBgQDE3Q6w+D8DbhtOHAvAvYDjrETA82nommJgFC1T1yb0Dx8mpJtK
i/OnLDJNeRE5cGVeiK5YwTmDHFyUX3wpHjUnQ0lfp1yWszXjOlA3MUllmmI/qAWA
eUmiz8bo8EIZ78aw2CAc7vWounxH2I+71835hKbEdPNoL6vuX1fu8wxVOQKBgEZc
GXmuzLbtxhiw+jubuo/4ZXUri6o4QtvlAzffEmNcNFkqu7YgDO89aNOnRWqwpVyx
ct2RU2rHfL2O2PiCtl3daNCqLexX09UQEYmTtQqHGMlDqqW3Oo81CKQ5PTbwYg6n
dLJaTqz8t5eCIj9uwQhZAtPpOHkHH+ZRlzq711zBAoGBAMYE4jk3+0u8jIDsj1/d
4gPDy/wjvNi4OJm2Tl5vusa1XvYQSUWlDCaX/BMhTtzXk/QKpn1pn4QT+QpHVrSd
WXraVueXSiuB3OcWNzcJyNEhrlJXVEB0Bah+9gKWFzzugdMyDM7bfDZ0uQwgIrQP
+iremSrTSTw9YcZ7MXORohEn
-----END PRIVATE KEY-----"""
client_email = "gads-mersalg@gads-mersalg.iam.gserviceaccount.com"
client_id = "115256778512221683970"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/gads-mersalg%40gads-mersalg.iam.gserviceaccount.com"
universe_domain = "googleapis.com"